In [1]:
# Import library
import numpy as np
from numpy import pi

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
try:
    /content/drive/MyDrive
except NameError:
    pass

In [4]:
a = np.genfromtxt('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', dtype=float, delimiter=',')

# 1. Знайти в датасеті таргет та видалити цю колонку з датасету (видаляти за індексом)

In [5]:
a.shape

(150, 5)

Target column has `string` type, after type coercion its value will be Not a Number (NaN). So we can get its index by finding which cell of any row has `NaN` value using `numpy.isnan` function.

In [6]:
target_index = np.where(np.isnan(a[0]))[0][0]

In [7]:
# a = a[:, : target_index]
a = np.delete(a, target_index, axis=1)
a.shape

(150, 4)

# 2. Перетворити колонки, що залишились в 2D масив (або впевнитись, що це уже 2D масив)

In [8]:
# Just for checking purpose
a = np.ravel(a)

In [9]:
if a.ndim != 2:

    # The number of columns is 4 according to the dataset
    a = np.reshape(a.ravel(), (a.size // 4, 4))
    print(f"Reshaped dataset to 2-dimensional matrix with shape: {a.shape}")
else:
    print("Dataset is already a 2-dimensional matrix")

Reshaped dataset to 2-dimensional matrix with shape: (150, 4)


# 3. Порахувати mean, median, standard deviation для 1-ї колонки

In [10]:
print(f"Mean of the first collumn is:\t{a[:, 0].mean()}")
print(f"Median of the first collumn is:\t{np.median(a[:, 0])}")
print(f"Std of the first collumn is:\t{np.std(a[:, 0])}")

Mean of the first collumn is:	5.843333333333334
Median of the first collumn is:	5.8
Std of the first collumn is:	0.8253012917851409


# 4. Вставити 20 значень np.nan на випадкові позиції в масиві (при використанні звичайного рандому можуть накластись позиції, тому знайти рішення, яке гарантує 20 унікальних позицій)

In [11]:
rng = np.random.default_rng()
nan_rows = rng.choice(a.shape[0], size=20, replace=False)
nan_cols = rng.choice(a.shape[1], size=20)
a[nan_rows, nan_cols] = np.nan

# 5. Знайти позиції вставлених значень np.nan в 1-й колонці

In [12]:
np.where(np.isnan(a[:, 0]))[0]

array([  3,  23, 113, 117, 128, 136, 148])

# 6. Відфільтрувати массив за умовою: значення в 3-й колонці > 1.5 та значения в 1-й колонці < 5.0 (зберегти у іншу змінну)

In [13]:
a[(a[:, 2] > 1.5) & (a[:, 0] < 5.0)]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, nan, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

# 7. Замінити всі значення np.nan на 0

In [14]:
a[np.isnan(a)] = 0

# 8. Порахувати всі унікальні значення в массиві та вивести їх разом із кількістю

In [15]:
unique_values, unique_counts = np.unique(a, return_counts=True)
unique_values, unique_counts

(array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 1. , 1.1, 1.2, 1.3, 1.4, 1.5,
        1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8,
        2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. , 4.1,
        4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2, 5.3, 5.4,
        5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7,
        6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.6, 7.7, 7.9]),
 array([20,  6, 28,  7,  7,  1,  1,  8,  4,  7, 20, 19, 25, 11,  6, 12,  6,
         7,  6,  4, 12,  6, 10,  5,  9, 14, 10, 27, 10, 13,  8, 12,  8,  4,
         4,  5,  5,  6,  4,  5,  3,  8,  9,  5,  7,  9, 10, 14, 16,  6,  3,
         8, 10, 11, 10, 10,  5,  8,  9,  3,  9,  7,  5,  3, 10,  3,  5,  1,
         1,  3,  1,  1,  1,  3,  1]))

# 9. Розбити масив по вертикалі на 2 рівні частини (не використовувати абсолютні числа, мають бути два массиви по 4 колонки)

In [16]:
lower, upper = np.split(a, 2)

In [17]:
print(f"{a.shape} = {lower.shape} + {upper.shape}")

(150, 4) = (75, 4) + (75, 4)


# 10. Відсортувати обидва массиви по 1-й колонці: 1-й за збільшенням, 2-й за зменшенням

In [18]:
lower = lower[lower[:, 0].argsort()]

In [19]:
print(f"{lower[0, 0]} = {lower.min(axis=0)[0]}, {lower[-1, 0]} = {lower.max(axis=0)[0]}")

0.0 = 0.0, 7.0 = 7.0


In [20]:
upper = upper[(-upper[:, 0]).argsort()]
# upper = upper[upper[:, 0].argsort()[::-1]]

In [21]:
print(f"{upper[-1, 0]} = {upper.min(axis=0)[0]}, {upper[0, 0]} = {upper.max(axis=0)[0]}")

0.0 = 0.0, 7.9 = 7.9


# 11. Зібрати обидва массиви в одне ціле

In [22]:
new_arr = np.vstack((lower, upper))
print(new_arr.shape == a.shape)

True


# 12. Знайти найбільш часто повторюване значення в массиві

Since we have unique values and their counts from (8), let's just find the argmax of the counts and use this index for unique values. After that let's check the result with `scipy.stats.mode` function result as the reference.

In [23]:
from scipy import stats
print(
    unique_values[np.argmax(unique_counts)],
    unique_values[np.argmax(unique_counts)] == stats.mode(a, axis=None).mode
)

0.2 True


# 13. Написати функцію, яка б множила всі значення в колонці, які менше середнього значения в цій колонці, на 2, і ділила інші значення на 4.

In [24]:
def func(arr):
    assert arr.ndim == 1
    mask = arr < arr.mean()
    arr[mask] *= 2.0
    arr[~mask] /= 4.0
    return arr

# 14. Застосувати отриману функцію до 3-ї колонки


In [25]:
print(new_arr[2])
new_arr[2] = func(new_arr[2])
print(new_arr[2])

[4.3 3.  1.1 0.1]
[1.075 0.75  2.2   0.2  ]
